AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Query the DB for file data and generate a signed preview URL
Resources:
  getFileData:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: Query the DB for file data and generate a signed preview URL
      MemorySize: 256
      Timeout: 3
      Role: 'arn:aws:iam::670324316752:role/dynamoDB-get-query-S3-get'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /gettrackinfo
            Method: GET
